### PR TITLE
[16.0] [MIG] l10n_it_withholding_tax

### PR DESCRIPTION
**Pull request by TheMule71**

### CODE REVIEW

**Review by marco-marchiori — APPROVED** [review]
Functional review:
configured new withholding tax ("1040", rate 20%), and a specific fiscal position for a supplier
entered an invoice
- correctly recognized the supplier
- correctly withheld 20%
- whttx reported into statements
- whttx reported into moves

**Review by tafaRU — APPROVED** [review]
Review tecnica: solo un commento, non bloccante, il resto LGTM :+1:

**Pull request merged**
