### PR TITLE
[FIX] No put in pack if package is without details

### PR DESCRIPTION
**Pull request by OpenCode**

### CODE REVIEW

**Comment by andrea4ever** [comment]
:+1:

**Comment by eLBati** [comment]
Thanks @OpenCode 
This has conflicts, please rebase

**Comment by OpenCode** [comment]
@eLBati Rebase done. Can I merge it?

**Comment by eLBati** [comment]
:+1:

**Comment by eLBati** [comment]
To 9.0 with https://github.com/OCA/l10n-italy/pull/184/commits/41c6b88a2f5880045139991b783c6e3f92ac3039

Also, please review https://github.com/OCA/l10n-italy/pull/184

**Comment by andrea4ever** [comment]
Merged

2 of 3 checks passed

**Pull request merged**
