### PR TITLE
Fix issue https://github.com/OCA/l10n-italy/issues/1828

### PR DESCRIPTION
**Pull request by SimoneVagile**
Fix issue [https://github.com/OCA/l10n-italy/issues/1828](https://github.com/OCA/l10n-italy/issues/1828)

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

### CODE REVIEW

**Review by matteoopenf — APPROVED** [review]

**Comment by matteoopenf** [comment]
> Fix issue #1828
> 
> --
> Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

Grazie

**Review by fredzamoabg — APPROVED** [review]

**Comment by matteoopenf** [comment]
@eLBati possiamo riprovare a mergiare?

**Comment by matteoopenf** [comment]
> /ocabot merge patch

Grazie

**Pull request merged**
