### PR TITLE
[IMP] Ricevute bancarie "Al dopo incasso"

### PR DESCRIPTION
**Pull request by SirAionTech**
Implementa https://github.com/OCA/l10n-italy/issues/2950 per `16.0`.
Risolve https://github.com/OCA/l10n-italy/issues/3814 per `16.0`.

Forward port di https://github.com/OCA/l10n-italy/pull/2951.

### CODE REVIEW

**Comment by SirAionTech** [comment]
Fatto rebase per risolvere i conflitti

**Review by MaurizioPellegrinet — APPROVED** [review]
Test funzionale: OK

**Review by andreampiovesana — APPROVED** [review]
LGTM

**Pull request merged**
