### PR TITLE
[FIX] l10n_it_fatturapa_pec: https://github.com/OCA/l10n-italy/issues/1037

### PR DESCRIPTION
**Pull request by SimoRubi**
Fix https://github.com/OCA/l10n-italy/issues/1037

### CODE REVIEW

**Comment by SimoRubi** [comment]
@GSLabIt please check if this solves your issue, thanks

**Comment by GSLabIt** [comment]
@SimoRubi, yes ..it seems to be fixed. So problem was label pointing to an unknown field?

**Comment by SimoRubi** [comment]
@GSLabIt yes, debugging the JS I discovered that the problem was the `label` tag

**Comment by SimoRubi** [comment]
Fixed up commits

**Comment by marcelofrare** [comment]
Aggiungo che testata in locale sulla mia installazione, mi ha risolto il problema.

**Pull request merged**
