### PR TITLE
[14.0] [FIX] github pre-commit action: pin python version to 3.11 in repository

### PR DESCRIPTION
**Pull request by renda-dev**
As previously stated in https://github.com/OCA/oca-addons-repo-template/pull/214, I'm bringing this change to this repo in version 14.0

CC: @OCA/local-italy-developers, @pedrobaeza

### CODE REVIEW

**Review by matteoopenf — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@tafaRU @OpenCode merge?

**Comment by tafaRU** [comment]
@francesco-ooops preferei attendere https://github.com/OCA/l10n-italy/pull/3685#issuecomment-1785370461

**Comment by francesco-ooops** [comment]
@OCA/local-italy-maintainers questa si può chiudere

**Comment by tafaRU** [comment]
Closing in favor of https://github.com/OCA/l10n-italy/pull/3687

**Pull request closed without merging**
