### PR TITLE
[FIX] l10n_it_fiscal_document_type: license must be AGPL since it depends on AGPL modules

### PR DESCRIPTION
**Pull request by dreispt**
image

### CODE REVIEW

**Review by simahawk — COMMENTED** [review]
@alessandrocamilli @eLBati can you check if it is ok for you and if this affects other modules?

**Comment by eLBati** [comment]
@simahawk it should be OK. Ref https://github.com/OCA/l10n-italy/pull/2360#issuecomment-885468210

**Review by eLBati — APPROVED** [review]
@dreispt thanks!

**Review by scigghia — APPROVED** [review]

**Pull request merged**
