### PR TITLE
[14.0] dotfiles update needs manual intervention

### PR DESCRIPTION
**Pull request by etobella**
Dear maintainer,

After updating the dotfiles, `pre-commit run -a`
fails in a manner that cannot be resolved automatically.

Can you please have a look, fix and merge?

Thanks,

### CODE REVIEW

**Comment by aleuffre** [comment]
Starting to work on this

**Comment by matteoopenf** [comment]
but the pre-commit not works

**Comment by aleuffre** [comment]
> but the pre-commit not works

precisely, I'm working to fix the pre-commit issues

**Comment by aleuffre** [comment]
But pre-commit is working, it's just that new checks were added. It's the same deal in every repo.

If you check the pre-commit logs, it's only failing because the modules are not up to standard, and often use deprecated syntax or dangerous functions such as `position="replace"`

This PR has been generated by the mass update of all repos from https://github.com/OCA/oca-addons-repo-template/ . #3684 just manually applied one of the changes as a stopgap, but this contains that change and more. This one will have to be merged eventually, in order to stay up to date with the rest of OCA.

**Pull request merged**
