### PR TITLE
[ADD] Runbot Status and Code Climate to README

### PR DESCRIPTION
**Pull request by tafaRU**

### CODE REVIEW

**Comment by eLBati** [comment]
:+1: thanks

**Comment by simahawk** [comment]
:+1:

**Comment by andrea4ever** [comment]
:+1:

**Comment by eLBati** [comment]
@tafaRU could you do the same for 9.0?

**Comment by tafaRU** [comment]
@eLBati, sure.

**Comment by tafaRU** [comment]
Please also review https://github.com/OCA/l10n-italy/pull/160

**Pull request merged**
