### PR TITLE
14.0 mig l10n_it_delivery_note_batch

### PR DESCRIPTION
**Pull request by fredzamoabg**
migrazione modulo l10n_it_delivery_note-batch

dipende da #1962

### CODE REVIEW

**Review by andreampiovesana — APPROVED** [review]
functional test ok

**Review by marcelofrare — APPROVED** [review]
works properly

**Comment by tafaRU** [comment]
@fredzamoabg puoi fare rebase? Per risolvere https://discord.com/channels/753902328494424064/753902328494424070/835123866040533012

**Comment by fredzamoabg** [comment]
> @fredzamoabg puoi fare rebase? Per risolvere https://discord.com/channels/753902328494424064/753902328494424070/835123866040533012

fatto

**Pull request closed without merging**
