### PR TITLE
[16.0] IMP l10n_it_vat_registries: ordering option

### PR DESCRIPTION
**Pull request by eLBati**
https://github.com/OCA/l10n-italy/issues/1414

### CODE REVIEW

**Comment by mrcast** [comment]
@eLBati trying to start ruboat I obtain "503 Service Unavailable". Can you please help me?

**Comment by eLBati** [comment]
> @eLBati trying to start ruboat I obtain "503 Service Unavailable". Can you please help me?

Non rilevo problemi su http://oca-l10n-italy-16-0-pr3971-921c9ae669c5.runboat.odoo-community.org

**Review by mrcast — APPROVED** [review]
Functional test, ok for me.

**Review by Borruso — APPROVED** [review]
LGTM

**Review by sergiocorato — APPROVED** [review]
Grazie

**Pull request merged**
