### PR TITLE
Fix partner retrieve from sale order

### PR DESCRIPTION
**Pull request by redondo81**

### CODE REVIEW

**Comment by tafaRU** [comment]
@redondo81, thanks for your contrib but this improvement is been already merged. Please see https://github.com/OCA/l10n-italy/pull/219

**Comment by tafaRU** [comment]
You need to update https://github.com/odoo-isa/l10n-italy/tree/8.0
I close then.

**Comment by redondo81** [comment]
ok, thank you very much. I download now the latest version...

**Comment by eLBati** [comment]
Mi pare che questa fix sia ancora necessaria:
https://github.com/OCA/l10n-italy/blob/8.0/l10n_it_ddt/wizard/ddt_from_picking.py#L50
il campo ```partner``` di ```sale.order``` non esiste

@redondo81 puoi riaprire questa PR?
Grazie

**Comment by tafaRU** [comment]
@eLBati, @redondo81 opened: https://github.com/OCA/l10n-italy/pull/229

**Pull request closed without merging**
