### PR TITLE
[16.0][FIX] l10n_it_reverse_charge: fix case there is a line with abbuoni

### PR DESCRIPTION
**Pull request by Borruso**
Risolve https://github.com/OCA/l10n-italy/issues/3581

### CODE REVIEW

**Review by andreampiovesana — APPROVED** [review]
LGTM

**Review by MaurizioPellegrinet — APPROVED** [review]
LGTM

**Review by marcelofrare — APPROVED** [review]
lgtm

**Comment by andreampiovesana** [comment]
merge?

**Pull request merged**
