### PR TITLE
[12.0][FIX] l10n_it_fatturapa_pec: Change test_sender_error to work fine

### PR DESCRIPTION
**Pull request by victoralmau**
Changed `test_sender_error` to work fine because actually have errors in tests.

@Tecnativa TT26985

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Seems correct technically, although functionally, I haven't dug yet enough.

**Comment by eLBati** [comment]
Why should `send_via_pec` raise error?

**Comment by victoralmau** [comment]
I do not know the reasons for the test, I have only created the PR to solve it because currently the tests fail.
Perhaps the creator of the addon knows why.

**Comment by eLBati** [comment]
I don't see failing builds for 12.0:
https://travis-ci.com/github/OCA/l10n-italy/branches

**Comment by victoralmau** [comment]
Hello, you are right, currently in branch 12.0 the error does not exist and therefore this PR is not necessary.
I close the PR.

**Pull request closed without merging**
