### PR TITLE
[FIX] assets_management: correct permission management

### PR DESCRIPTION
**Pull request by PicchiSeba**
The previous version allowed `base.group_user` to access the assets with full read/write permissions from their url even if they were hidden from them in the menus.
With this PR we aim to correctly manage user permissions, already implemented but never used.

Also, child menu items were being used with redundant group permission already specified by the parent.

### CODE REVIEW

**Review by aleuffre — APPROVED** [review]

**Comment by aleuffre** [comment]
Avrei proposto anche due livelli ma per ora partiamo così, meglio della situazione precedente.

**Review by sergiocorato — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@PicchiSeba puoi far ricostruire il runboat?

**Pull request merged**
