### PR TITLE
[FIX] l10n_it_account: Fixed context overwrite in account tax

### PR DESCRIPTION
**Pull request by LorenzoC0**
Fix necessaria per far funzionare #4338

### CODE REVIEW

**Review by eLBati — APPROVED** [review]

**Review by andreampiovesana — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@eLBati @LorenzoC0 è da fare anche per v16? 

se sì aprite la issue pls

**Comment by eLBati** [comment]
@francesco-ooops not affected https://github.com/OCA/l10n-italy/blob/1a598c168f13c6c7878db03799beea2da3f96f5a/l10n_it_account/models/account_tax.py#L168

**Pull request merged**
