### PR TITLE
[12.0][FIX] l10n_it_fatturapa_pec: Fix test_sender_error

### PR DESCRIPTION
**Pull request by victoralmau**
Fix test_sender_error

@Tecnativa TT26985

### CODE REVIEW

**Comment by eLBati** [comment]
What does this fix?

**Comment by victoralmau** [comment]
> What does this fix?

Because an error appear in travis ci related to mail error test.

**Comment by eLBati** [comment]
@victoralmau please provide more information

**Comment by victoralmau** [comment]
> @victoralmau please provide more information

Ok, https://travis-ci.com/github/OCA/l10n-italy/jobs/459547291#L3418 appear an error in Travis

**Review by eLBati — APPROVED** [review]
Ok, thanks. This does not compromise green result https://travis-ci.com/github/OCA/l10n-italy/jobs/459957496#L3127 but it is good to have

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
