### PR TITLE
[FIX] Get partners for ddt from origin sale of picking

### PR DESCRIPTION
**Pull request by OpenCode**
PR for https://github.com/OCA/l10n-italy/issues/215

### CODE REVIEW

**Comment by scigghia** [comment]
:+1:

**Comment by paolovalier** [comment]
:+1:

**Comment by eLBati** [comment]
Thanks @OpenCode 
github says
> This branch has conflicts that must be resolved

Please rebase

**Comment by OpenCode** [comment]
@eLBati rebase done. Travis red for another module.

**Comment by eLBati** [comment]
@OpenCode :+1: thanks

About red travis see https://github.com/OCA/l10n-italy/pull/225

**Comment by redondo81** [comment]
I read the code, but the problem is in this line:
values['partner_id'] = sale.partner.id
the correct value is values['partner_id'] = sale.**partner_id**.id
Object sale is releted with this name partner_id not partner.

**Pull request merged**
