### PR TITLE
[8.0] FIX travis: Unable to install module "l10n_it_fatturapa" because an e…

### PR DESCRIPTION
**Pull request by vincenzoterzulli**
#1495

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

### CODE REVIEW

**Comment by eLBati** [comment]
Let's just wait for @oca-clabot to become aware of your sign

**Comment by pedrobaeza** [comment]
> Let's just wait for @oca-clabot to become aware of your sign

It only replies when there's an extra commit from the cla signer.

**Comment by sergiocorato** [comment]
@vincenzoterzulli can you push another commit?

**Pull request merged**
