### PR TITLE
[IMP] l10n_it_delivery_note: add maintainers

### PR DESCRIPTION
**Pull request by aleuffre**
Proposing to add myself and @renda-dev to the list of maintainers for this module.

### CODE REVIEW

**Review by tafaRU — APPROVED** [review]

**Review by MarcoCalcagni — APPROVED** [review]

**Comment by renda-dev** [comment]
Now it should be good to go, thanks! @MarcoCalcagni

**Comment by francesco-ooops** [comment]
@tafaRU puoi riprovare?

**Comment by francesco-ooops** [comment]
@eLBati @tafaRU @MarcoCalcagni riproviamo il merge?

**Pull request merged**
