### PR TITLE
[14.0][MIG] l10n_it_pos_fatturapa: Migration to 14.0

### PR DESCRIPTION
**Pull request by iwkse**

### CODE REVIEW

**Comment by iwkse** [comment]
@eLBati Hi! Do you have idea why is it failing? It doesn't seem related to the module
Thank you

**Comment by iwkse** [comment]
> @eLBati Hi! Do you have idea why is it failing? It doesn't seem related to the module Thank you

@GSLabIt helped me to spot some issues, I will fix them and try again

**Comment by iwkse** [comment]
This module depends on this PR https://github.com/OCA/pos/pull/744

**Comment by francesco-ooops** [comment]
@OCA/local-italy-maintainers si può chiudere

**Comment by tafaRU** [comment]
Chiudo in favore di https://github.com/OCA/l10n-italy/pull/3482

**Pull request closed without merging**
