### PR TITLE
[12.0][IMP] l10n_it_fatturapa_pec state related source strings

### PR DESCRIPTION
**Pull request by primes2h**
Add 'state' reference in source strings to simplify translation work (avoid issues with plural forms).

### CODE REVIEW

**Comment by primes2h** [comment]
Up

**Comment by eLBati** [comment]
Beta module, merging.

@primes2h please then verify weblate translations.
Thanks

**Comment by primes2h** [comment]
> Beta module, merging.
> 
> @primes2h please then verify weblate translations.
> Thanks

Sure :+1:

**Comment by sbidoul** [comment]
I'm running out of ideas. Opening a discussion at weblate https://github.com/WeblateOrg/weblate/issues/2107#issuecomment-450198552

In the meantime I ran a manual update for l10n-italy, please check it.

**Comment by primes2h** [comment]
> I'm running out of ideas. Opening a discussion at weblate [WeblateOrg/weblate#2107 (comment)](https://github.com/WeblateOrg/weblate/issues/2107#issuecomment-450198552)

:+1: 
 
> In the meantime I ran a manual update for l10n-italy, please check it.

Updated, thanks!

**Comment by primes2h** [comment]
@sbidoul 

I ran odoo-bin with --i18n-overwrite option to update db translations and I got several messages like this one:

2018-12-28 20:25:45,226 8851 INFO odoo12-test odoo.tools.translate: Translation 'First name' (model, ir.model.fields,field_description, partner_firstname.field_res_partner_firstname) not found in reference pot, skipping

In fact I found out that same problem affects:
at least other 2 OCA modules, partner-contact/partner_firstname and account-financial-reporting/account_tax_balance (12.0).
pot files are updated but it.po ones are not.

but, OCB modules are affected too:
e.g. account
Last week I opened this PR:
https://github.com/odoo/odoo/pull/29690
merged 3 days ago.
In OCB, account.pot file has been updated accordingly, it.po not.

I hope these findings help you.
 
P.S.: could you please update these modules manually? Thanks.

**Comment by sbidoul** [comment]
@primes2h I ran a manual update on all OCA.

Regarding OCB, we don't manage the OCB translations in OCA. You should translate on Odoo's transifex and they will be brought to OCB as part of the nightly OCB sync with upstream Odoo.

**Comment by primes2h** [comment]
@sbidoul 
Thanks!

About OCB, I was referring to mismatch between .pot and .po source strings. 
You mean that Odoo/Transifex sync is not on a daily basis (as OCB/Odoo code is)?

**Comment by sbidoul** [comment]
> You mean that Odoo/Transifex sync is not on a daily basis (as OCB/Odoo code is)?

I don't know. Have you checked on Transifex if the new terms are there? Perhaps the .po is updated only when something is translated on transifex. @mart-e must know.

**Comment by mart-e** [comment]
Hi,

The usual flow is the following:
1. the .pot is updated on odoo/odoo on github
2. transifex watches the .pot file, it notices the changes and update the resource  <-- this step failed
3. a new translation is made to transifex
4. the translations are synced from transifex to odoo/odoo every Sunday
5. OCA/OCB sync lasts commits from odoo/odoo in their daily sync

The step 2 failed as Transifex somehow got an error when reading the file on github. I have manually forced the sync and the new terms [are on Transifex](https://www.transifex.com/odoo/odoo-12/translate/#it/account/151500937?q=text%3A'has+been+created+from').
At the next synchronisation from transifex to github, the it.po file will be updated.

**Comment by primes2h** [comment]
@mart-e 
Thanks for the clarification.

**Comment by primes2h** [comment]
> Hi,
> 
> The usual flow is the following:
> 
>     1. the .pot is updated on odoo/odoo on github
> 
>     2. transifex watches the .pot file, it notices the changes and update the resource  <-- this step failed
> 
>     3. a new translation is made to transifex
> 
>     4. the translations are synced from transifex to odoo/odoo every Sunday
> 
>     5. OCA/OCB sync lasts commits from odoo/odoo in their daily sync
> 
> 
> The step 2 failed as Transifex somehow got an error when reading the file on github. I have manually forced the sync and the new terms [are on Transifex](https://www.transifex.com/odoo/odoo-12/translate/#it/account/151500937?q=text%3A'has+been+created+from').
> At the next synchronisation from transifex to github, the it.po file will be updated.

@mart-e
Thanks for the clarification.

**Pull request merged**
