### PR TITLE
[8.0][FIX] date format in riba line created

### PR DESCRIPTION
**Pull request by sergiocorato**
Riba lines created from move lines have date non formatted for Italy (date is a char field). With this mp date are put correctly.

### CODE REVIEW

**Comment by OpenCode** [comment]
I think is better to convert field to date type so Odoo can format it based on user language

**Comment by sergiocorato** [comment]
This is not possible because when the ri.ba. are grouped by partner by date due, this field is used to summarize multiple invoice dates

**Comment by eLBati** [comment]
What would happen when applying this change to existing DBs?

**Comment by sergiocorato** [comment]
With this MP, nothing happens to existing DBs, only new record are translated correctly. The previous records remain in the english format (field is a char).
OpenCode comment is not applicable in this case.

**Comment by eLBati** [comment]
@sergiocorato ok, thanks. Could you also do this for 10.0?

**Comment by eLBati** [comment]
@OpenCode mergio?

**Comment by sergiocorato** [comment]
@OpenCode un attimo che la sistemo

**Comment by sergiocorato** [comment]
@OpenCode  @eLBati fatto, ho aggiornato anche la versione

**Pull request merged**
