### PR TITLE
[8.0] l10n_it_regions

### PR DESCRIPTION
**Pull request by dcorio**
New module that imports Italian regions from geonames and links them to provinces

### CODE REVIEW

**Comment by eLBati** [comment]
Hi @dcorio what's the destiny of this?

**Comment by dcorio** [comment]
@eLBati @OpenCode i'm sure there's a lot of things to be fixed, but i'm creating this pr so we can work on this and eventually merge it

**Comment by OpenCode** [comment]
@dcorio It's good for me

**Comment by scigghia** [comment]
:+1: 
also for me

**Comment by eLBati** [comment]
@dcorio so can this be reviewed? Shall I remove the WIP tag?

**Comment by dcorio** [comment]
@eLBati hi, yes...just removed the wip tag

**Comment by OpenCode** [comment]
@eLBati Runbot is red. 
l10n_it_base_location_geonames_import missing

**Comment by eLBati** [comment]
@dcorio please rebase, to include ```l10n_it_base_location_geonames_import```

**Comment by OpenCode** [comment]
@dcorio news?

**Comment by scigghia** [comment]
@dcorio news?

**Comment by dcorio** [comment]
@scigghia can't work on this right now

**Comment by scigghia** [comment]
continuiamo qui: https://github.com/OCA/l10n-italy/pull/375

**Pull request closed without merging**
