### PR TITLE
[10.0] add account_invoice_report_ddt_group

### PR DESCRIPTION
**Pull request by eLBati**
Account Invoice Report DDT Group
================================

This modules modifies the invoice report, so that the invoice lines are grouped by the DDT that generated them

Depends on https://github.com/OCA/l10n-italy/pull/320

### CODE REVIEW

**Comment by tafaRU** [comment]
@eLBati, please see https://github.com/eLBati/l10n-italy/pull/91

**Comment by tafaRU** [comment]
@eLBati, please restart build considering that https://github.com/OCA/l10n-italy/pull/320 has been merged.

**Comment by eLBati** [comment]
We need to merge https://github.com/eLBati/l10n-italy/pull/94 to fix tests

**Comment by hurrinico** [comment]
Tested Locally :+1 IMHO

**Pull request merged**
