### PR TITLE
[16.0] ADD l10n_it_withholding_tax_financial_report: Make l10n_it_withholding_tax and account_financial_report work together

### LINKED ISSUE #4241: Ritenute: Rendicontazione Varie per i Fornitori
**Is your feature request related to a problem ?**
SI.

**Describe the solution you'd like**
Visualizzare e/o Considerare l'importo corretto del debito fornitori

## Modulo Principale
- Ritenute di Acconto

## Moduli in cui si verifica il problema 
- Rendicontazione: Partite Aperte
- Rendicontazione: Debito Scaduto
- Rendicontazione: Scadenzario Clienti/Fornitori
- Mandati o Ordini di Pagamento (CBI)
- Prestiti

## Describe the bug
Quando si registrano fatture oppure Note Credito Fornitori con Ritenute di Acconto nei moduli citati in precedenza, non viene considerato il netto che deve pagare il fornitore ma il totale documento.

## To Reproduce
**Affected versions**:

- [ ] 14.0
  - [x] Rendicontazione: Partite Aperte - https://github.com/OCA/l10n-italy/pull/4260
  - [ ] Rendicontazione: Debito Scaduto
  - [ ] Rendicontazione: Scadenzario Clienti/Fornitori
  - [x] Mandati o Ordini di Pagamento (CBI) - https://github.com/OCA/l10n-italy/pull/4352
  - [ ] Prestiti
- [ ] 16.0 
  - [x] Rendicontazione: Partite Aperte - https://github.com/OCA/l10n-italy/pull/4120
  - [ ] Rendicontazione: Debito Scaduto
  - [ ] Rendicontazione: Scadenzario Clienti/Fornitori
  - [x] Mandati o Ordini di Pagamento (CBI) - https://github.com/OCA/l10n-italy/pull/3985
  - [ ] Prestiti

1. Inserimento Fattura con Ritenuta di Acconto
2. Rilevare il netto da pagare per quella fattura
3. Utilizzare i moduli indicati in precedenza per constatare il debito esposto e/o estratto per la fattura inserita al punto 1 

**Expected behavior**
Chiaramente ci si aspetta che l'intervento che si farà farà si che si possa avere una situazione debitoria corretta sia dal punto di vista di consultazione che dal punto di vista di estrazione dati (ordini di pagamento) 

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)
- Quello che posso segnalare è che sembra che il modulo dello Split Payment, per cui vengono emesse fatture con un netto a pagare diverso dal totale documento, almeno delle consultazioni non hanno la stessa problematica.
- Io ho notato il BUG in questi moduli ma potrebbero essercene altri di cui non sono a conoscenza dell'esistenza.
-Il problema si potrebbe verificare anche per la parte attiva ovvero fatture/note credito di vendita con ritenute di acconto

### PR DESCRIPTION
**Pull request by eLBati**
Risolve il punto "partite aperte" della https://github.com/OCA/l10n-italy/issues/4241

### CODE REVIEW

**Comment by francesco-ooops** [comment]
@eLBati issue please

**Review by GSLabIt — APPROVED** [review]

**Review by MaurizioPellegrinet — APPROVED** [review]
Test funzionale: OK

**Pull request merged**
