### PR TITLE
[8.0][ADD] l10n_it_reverse_charge module

### PR DESCRIPTION
**Pull request by tafaRU**

### CODE REVIEW

**Comment by tafaRU** [comment]
@dcorio,

**Comment by tafaRU** [comment]
@dcorio, l'ho riaperta, mi sa che hai confuso le PR :wink:

**Comment by dcorio** [comment]
@tafaRU sorry

**Comment by eLBati** [comment]
@tafaRU @dcorio Fixed lint and squashed

**Comment by eLBati** [comment]
It seems travis has problems with ```base_location_geonames_import```

**Comment by eLBati** [comment]
> It seems travis has problems with base_location_geonames_import

now solved

**Pull request merged**
