### PR TITLE
[16.0] [FIX] l10n_it_withholding_tax withholding tax label not shown 

### LINKED ISSUE #3263: 16.0 l10n_it_withholding_tax - Errata etichetta
## Describe the bug
L'etichetta relativa alla registrazione della ritenuta è errata.
Attualmente scrive **Pagato il dd/mm/yyyy**, dove in realtà non è pagata ma solo registrata

## To Reproduce

1. Creo la ritenuta d'acconto
2. Imposto il'informazione fiscale sul partner
3. Creo una fattura fornitore
4. La valido
5. La pago

image

**Affected versions**:
16.0

**Expected behavior**
Dovrebbe usare l'etichetta **RdA registrata il dd/mm/yyyy** come succede sulla 14.0

image

### PR DESCRIPTION
**Pull request by primes2h**
Fix #3263

### CODE REVIEW

**Review by Borruso — APPROVED** [review]

**Review by marcelofrare — APPROVED** [review]
LGTM grazie!

**Review by andreampiovesana — APPROVED** [review]
LGTM

**Review by MaurizioPellegrinet — APPROVED** [review]
LGTM

**Pull request merged**
