### PR TITLE
[IMP] fatturapa_in Autofatture per autoconsumo TD27

### PR DESCRIPTION
**Pull request by SirTakobi**
Risolve https://github.com/OCA/l10n-italy/issues/3161 per `12.0`.
Backport di https://github.com/OCA/l10n-italy/pull/3162 + test.

Resolves: #3161

### CODE REVIEW

**Review by MarcoCalcagni — APPROVED** [review]
Ok test funzionali

**Review by mrcast — APPROVED** [review]
Functional test, ok!

**Pull request merged**
