### PR TITLE
[14.0][FIX] l10n_it_delivery_note: unlink DNs from invoices at Cancel

### LINKED ISSUE #4190: l10n_it_delivery_note: i DDT rimangono collegati a fatture annullate
## Module
l10n_it_delivery_note

## Describe the bug
I DDT vengono rimessi a fatturabili in caso di cancellazione (delete) di una fattura, ma non quando questa viene annullata (cancel).

## To Reproduce
**Affected versions**:

- [x] 16.0 #4191
- [x] 14.0 https://github.com/OCA/l10n-italy/pull/4226

1. Crea un SO, consegna la merce.
2. Fattura la merce o da SO o da DDT
3. Annulla (cancel) la fattura
4. Crea una nuova fattura da SO

I DDT rimangono collegati alla fattura annullata, non alla nuova.

**Expected behavior**
L'associazione tra fattura e DDT andrebbe rimossa anche quando una fattura viene annullata e i DDT dovrebbero essere ri-fatturabili.

**Additional context**
https://github.com/OCA/l10n-italy/blob/5995d0fff7baca2d413a4567a8ae0eba8f812e69/l10n_it_delivery_note/models/account_invoice.py#L147-L159
gestisce il caso di cancellazione (delete) della fattura. Dovrebbe succedere lo stesso anche in caso di annullamento (cancel).

### PR DESCRIPTION
**Pull request by toita86**
backport of https://github.com/OCA/l10n-italy/pull/4191
for the issue https://github.com/OCA/l10n-italy/issues/4190

### CODE REVIEW

**Review by HekkiMelody — APPROVED** [review]
Code review, LGTM

**Review by renda-dev — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
