### PR TITLE
Migration of account_vat_period_end_statement

### PR DESCRIPTION
**Pull request by tafaRU**
TODO
 - [ ] report

### CODE REVIEW

**Comment by dcorio** [comment]
wouldn't it be the case to rename to module to "l10n_it_vat_liquidation"?
the term "VAT Liquidation" is used worldwide AFAIK.

**Comment by eLBati** [comment]
On 9 May 2015 at 16:23, Davide Corio <notifications@github.com> wrote:

> wouldn't it be the case to rename to module to "l10n_it_vat_liquidation"?
> the term "VAT Liquidation" is used worldwide AFAIK.
>
>
>
It's ok with me

**Comment by dcorio** [comment]
i also noticed that most of the labels aren't properly shown. wrong grouping of fields?

**Comment by tafaRU** [comment]
> wrong grouping of fields?

Yes, indeed I set WIP :wink:
Any PR is obviously welcomed!

**Comment by dcorio** [comment]
NB: "vat liquidation" on Google = 604 records. "vat statement" on Google = 27.900 records

**Comment by DAMilani** [comment]
Questa PR è stata sostituita dalla seguente:

https://github.com/OCA/l10n-italy/pull/124

**Pull request closed without merging**
