### PR TITLE
[MIG] l10n_it_base_location_geonames_import: Migrated to 10.0

### PR DESCRIPTION
**Pull request by OpenCode**
WIP l10n_it_base_location_geonames_import migrated to 10.0

### CODE REVIEW

**Comment by OpenCode** [comment]
Need https://github.com/OCA/partner-contact/pull/317

**Comment by LeartS** [comment]
https://github.com/OCA/partner-contact/pull/317 has been merge, any news @OpenCode ?

**Comment by OpenCode** [comment]
@LeartS I need to work on it because i was waiting for merge of PR 317

**Comment by hurrinico** [comment]
@OpenCode any news on this PR? i've seen that travis is red 'cause depend on pr 317 that is merged now.
Maybe a rebase of your branch will fix the problem

**Comment by OpenCode** [comment]
@LeartS @hurrinico it works. I'll do a rebase

**Comment by OpenCode** [comment]
@hurrinico @LeartS 

Rebase: Done!
Test porting: Done!
Travis green: Done!
Squash in 1 commit: Done!

Do you feel the spring in the air?

**Comment by LeartS** [comment]
Great job! 👍

**Comment by hurrinico** [comment]
Great job 👍

**Pull request merged**
