### PR TITLE
[12.0] FIX fiscal_epos_print: fiscalprinter_payment_index must be set also for Discount on payment

### PR DESCRIPTION
**Pull request by eLBati**
image

image

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

### CODE REVIEW

**Review by GSLabIt — APPROVED** [review]
LGTM

**Review by mrcast — APPROVED** [review]
Test ok

**Review by TheMule71 — APPROVED** [review]
LGTM

**Comment by tafaRU** [comment]
> @eLBati The merge process could not start, because of exception 403 Must have admin access to view repository collaborators..

stesso errore [qui](https://github.com/OCA/OpenUpgrade/pull/2854#issuecomment-920090435)

**Comment by matteoopenf** [comment]
@eLBati  @tafaRU  https://github.community/t/github-api-collaborators-access-changed-today/201259 credo che sia dovuto a questo il problema che stiamo riscontrando

**Comment by tafaRU** [comment]
Riprovo dopo https://github.com/OCA/OpenUpgrade/pull/2854#issuecomment-920253832

**Comment by tafaRU** [comment]
@eLBati in base a https://github.com/OCA/OpenUpgrade/pull/2854#issuecomment-920217677 serve che tu usi i tuoi super poteri :superhero_man: per: 
> change the bot permissions

**Comment by tafaRU** [comment]
@eLBati GitHub ha fatto roolback delle ultime modifiche (vedi https://github.community/t/github-api-collaborators-access-changed-today/201259/17) pertanto puoi togliere ocabot da admin del repo.

**Pull request merged**
