### PR TITLE
11.0 fix l10n it decimal precision on fatturapa

### PR DESCRIPTION
**Pull request by As400it**
Descrizione del problema o della funzionalità: vedi issue https://github.com/OCA/l10n-italy/issues/1340

Comportamento attuale prima di questa PR:
questa pr sostituisce la https://github.com/OCA/l10n-italy/pull/1353 

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

### CODE REVIEW

**Comment by OpenCode** [comment]
@eLBati se mi dici come fare vorrei provare a megiare con OCA Bot. Grazie.

**Comment by eLBati** [comment]
@OpenCode https://github.com/OCA/oca-github-bot#commands
Quindi in questo caso userei `minor` come per la 12

**Comment by eLBati** [comment]
@sbidoul what should we do when this happens? https://github.com/OCA/l10n-italy/pull/1425#issuecomment-549761746

**Comment by sbidoul** [comment]
Oh, that is strange, because it is merged. So there is nothing to do.

I probably failed here:

https://github.com/OCA/oca-github-bot/blob/9e3608da786f3594ed8d711dc78c2aad84c42816/src/oca_github_bot/tasks/merge_bot.py#L139

which is a useless operation with the current merge strategy.

**Comment by eLBati** [comment]
@sbidoul thanks

**Pull request merged**
