### PR TITLE
[8.0] Porting l10n_it_corrispettivi

### PR DESCRIPTION
**Pull request by shakin89**
This is my first attempt to port a module to v 8.0

### CODE REVIEW

**Comment by eLBati** [comment]
Thanks @shakin89 
I see you started from ```l10n_it_corrispettivi``` version contained in 8.0 branch, but it is outdated. You should start porting from 7.0 branch.
See the diff between 7.0 version and your version:
https://gist.github.com/eLBati/d0b190881f72b356f2a2
As you can see, you removed some improvements made on 7.0 which must be kept (like ```from . import account```)

So, please copy the 7.0 version of the module to a new branch and apply your commits on it.
Thanks

**Comment by shakin89** [comment]
Ok, i've ported the improvement made in 7.0 version, i've compared all the files and aligned the 7.0 version to this one.

**Comment by eLBati** [comment]
This gives conflicts and should be rebased

**Comment by eLBati** [comment]
@shakin89 chiuderei questa PR per continuare il tuo lavoro sulla https://github.com/OCA/l10n-italy/pull/230  e sistemare le ultime cose per fare il merge.
Fammi sapere se OK per te

**Pull request closed without merging**
