### PR TITLE
[14.0] [REF] l10n_it_delivery_note: aggiornato report per trasferimento interno

### PR DESCRIPTION
**Pull request by renda-dev**
Backport di https://github.com/OCA/l10n-italy/pull/3583

Risolve https://github.com/OCA/l10n-italy/issues/3832

cc: @Borruso, @francesco-ooops

### CODE REVIEW

**Review by Borruso — APPROVED** [review]
LGTM

**Review by francesco-ooops — APPROVED** [review]
Funzionale ok

**Review by aleuffre — APPROVED** [review]
Code review

**Pull request merged**
