### PR TITLE
[FIX] l10n_it_fatturapa_pec: filename without colon

### PR DESCRIPTION
**Pull request by mde-spring**
Fix colon in filename

#3805 
#3500

### CODE REVIEW

**Review by SirAionTech — CHANGES_REQUESTED** [review]
Only code review, looks good to me.

Please fix the commit message and PR name/description: they should mention **colon** (the punctuation mark `:`) not **column**
image

**Comment by mde-spring** [comment]
@SirAionTech my bad 
Correction done

**Review by SirAionTech — APPROVED** [review]

**Review by odooNextev — APPROVED** [review]
LGTM

**Pull request merged**
