### PR TITLE
[8.0] add new module to export xml files in bulk: l10n_it_fatturapa_export_zip

### PR DESCRIPTION
**Pull request by sergiocorato**
v. 10 ~#949~ #1030

### CODE REVIEW

**Comment by scigghia** [comment]
testato e funzionante
tnx @sergiocorato

**Comment by CiroBoxHub** [comment]
:+1:

**Comment by eLBati** [comment]
Sulla https://github.com/OCA/l10n-italy/pull/1030 ho fatto diverse migliorie

**Comment by sergiocorato** [comment]
> Sulla #1030 ho fatto diverse migliorie

@eLBati ho riportato le migliorie qui

**Comment by sergiocorato** [comment]
@scigghia @CiroBoxHub potete testare con le ultime modifiche?

**Comment by eLBati** [comment]
@sergiocorato mancherebbero ancora alcune cosette presenti su 10.0 e non qua:
```
diff --git a/l10n_it_fatturapa_export_zip/wizard/export_fatturapa.py b/l10n_it_fatturapa_export_zip/wizard/export_fatturapa.py
index 07e1e79..410fda2 100644
--- a/l10n_it_fatturapa_export_zip/wizard/export_fatturapa.py
+++ b/l10n_it_fatturapa_export_zip/wizard/export_fatturapa.py
@@ -4,8 +4,8 @@ import base64
 import io
 import zipfile
 from datetime import datetime
-from openerp import models, api, fields, _
-from openerp.exceptions import Warning as UserError
+from odoo import models, api, fields, _
+from odoo.exceptions import UserError
 
 
 class WizardAccountInvoiceExport(models.TransientModel):
@@ -17,22 +17,22 @@ class WizardAccountInvoiceExport(models.TransientModel):
             _("E-invoice-export"), datetime.now().strftime('%Y%m%d%H%M'))
 
     data = fields.Binary("File", readonly=True)
-    name = fields.Char('Filename', default=_default_name)
+    name = fields.Char('Filename', default=_default_name, required=True)
 
     @api.multi
     def export_zip(self):
-        attachments = []
-        for att in self.env[self._context['active_model']].browse(
-                self._context['active_ids']):
-            attachments += [att]
+        self.ensure_one()
+        attachments = self.env[self.env.context['active_model']].browse(
+            self.env.context['active_ids'])
         for att in attachments:
             if att.exported_zip:
                 raise UserError(_(
                     "Attachment %s already exported. Remove ZIP file first"
-                ) % att.name)
+                ) % att.display_name)
             if not att.datas or not att.datas_fname:
                 raise UserError(
-                    _("Attachment %s does not have XML file") % att.name)
+                    _("Attachment %s does not have XML file")
+                    % att.display_name)
 
         fp = io.BytesIO()
         with zipfile.ZipFile(fp, mode="w") as zf:
@@ -40,17 +40,14 @@ class WizardAccountInvoiceExport(models.TransientModel):
                 zf.writestr(att.datas_fname, base64.b64decode(att.datas))
         fp.seek(0)
         data = fp.read()
-        export_report_name = 'E-Invoices XML'
-        if self.name:
-            export_report_name = self.name
         attach_vals = {
-            'name': export_report_name + '.zip',
-            'datas_fname': export_report_name + '.zip',
+            'name': self.name + '.zip',
+            'datas_fname': self.name + '.zip',
             'datas': base64.encodestring(data),
         }
         zip_att = self.env['ir.attachment'].create(attach_vals)
         for att in attachments:
-            att.exported_zip = zip_att.id
+            att.exported_zip = zip_att
         return {
             'view_type': 'form',
             'name': _("Export E-Invoices"),
@@ -58,5 +55,4 @@ class WizardAccountInvoiceExport(models.TransientModel):
             'view_mode': 'form',
             'res_model': 'ir.attachment',
             'type': 'ir.actions.act_window',
-            'context': self._context,
         }
```

**Comment by sergiocorato** [comment]
> @sergiocorato mancherebbero ancora alcune cosette presenti su 10.0 e non qua:
> 
> ```
> diff --git a/l10n_it_fatturapa_export_zip/wizard/export_fatturapa.py b/l10n_it_fatturapa_export_zip/wizard/export_fatturapa.py
> index 07e1e79..410fda2 100644
> --- a/l10n_it_fatturapa_export_zip/wizard/export_fatturapa.py
> +++ b/l10n_it_fatturapa_export_zip/wizard/export_fatturapa.py
> @@ -4,8 +4,8 @@ import base64
>  import io
>  import zipfile
>  from datetime import datetime
> -from openerp import models, api, fields, _
> -from openerp.exceptions import Warning as UserError
> +from odoo import models, api, fields, _
> +from odoo.exceptions import UserError
>  
>  
>  class WizardAccountInvoiceExport(models.TransientModel):
> @@ -17,22 +17,22 @@ class WizardAccountInvoiceExport(models.TransientModel):
>              _("E-invoice-export"), datetime.now().strftime('%Y%m%d%H%M'))
>  
>      data = fields.Binary("File", readonly=True)
> -    name = fields.Char('Filename', default=_default_name)
> +    name = fields.Char('Filename', default=_default_name, required=True)
>  
>      @api.multi
>      def export_zip(self):
> -        attachments = []
> -        for att in self.env[self._context['active_model']].browse(
> -                self._context['active_ids']):
> -            attachments += [att]
> +        self.ensure_one()
> +        attachments = self.env[self.env.context['active_model']].browse(
> +            self.env.context['active_ids'])
>          for att in attachments:
>              if att.exported_zip:
>                  raise UserError(_(
>                      "Attachment %s already exported. Remove ZIP file first"
> -                ) % att.name)
> +                ) % att.display_name)
>              if not att.datas or not att.datas_fname:
>                  raise UserError(
> -                    _("Attachment %s does not have XML file") % att.name)
> +                    _("Attachment %s does not have XML file")
> +                    % att.display_name)
>  
>          fp = io.BytesIO()
>          with zipfile.ZipFile(fp, mode="w") as zf:
> @@ -40,17 +40,14 @@ class WizardAccountInvoiceExport(models.TransientModel):
>                  zf.writestr(att.datas_fname, base64.b64decode(att.datas))
>          fp.seek(0)
>          data = fp.read()
> -        export_report_name = 'E-Invoices XML'
> -        if self.name:
> -            export_report_name = self.name
>          attach_vals = {
> -            'name': export_report_name + '.zip',
> -            'datas_fname': export_report_name + '.zip',
> +            'name': self.name + '.zip',
> +            'datas_fname': self.name + '.zip',
>              'datas': base64.encodestring(data),
>          }
>          zip_att = self.env['ir.attachment'].create(attach_vals)
>          for att in attachments:
> -            att.exported_zip = zip_att.id
> +            att.exported_zip = zip_att
>          return {
>              'view_type': 'form',
>              'name': _("Export E-Invoices"),
> @@ -58,5 +55,4 @@ class WizardAccountInvoiceExport(models.TransientModel):
>              'view_mode': 'form',
>              'res_model': 'ir.attachment',
>              'type': 'ir.actions.act_window',
> -            'context': self._context,
>          }
> ```

fatto

**Pull request merged**
