### PR TITLE
[SEC] l10n_it_fatturapa_out: fix unsafe eval

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by lepistone** [comment]
Same comment as in #193. Thanks!

**Comment by antespi** [comment]
:+1:

**Comment by eLBati** [comment]
Thanks @gurneyalex ,

tests are failing:
```
2016-02-15 09:19:36,874 23022 ERROR openerp_test openerp.addons.l10n_it_fatturapa_out.tests.test_fatturapa_xml_validation: ` ValueError: "name 'body' is not defined" while evaluating

2016-02-15 09:19:36,875 23022 ERROR openerp_test openerp.addons.l10n_it_fatturapa_out.tests.test_fatturapa_xml_validation: ` 'body.DatiGenerali.DatiOrdineAcquisto.append(documento)'
```

**Comment by gurneyalex** [comment]
@eLBati @lepistone updated to use getattr, which should fix the tests.

**Comment by lepistone** [comment]
Thanks! :+1:

**Comment by eLBati** [comment]
Thanks :+1:

**Pull request merged**
