### PR TITLE
Fix #1043 [11.0] l10n_it_ddt, corriere mancante

### LINKED ISSUE #1043: l10n_it_ddt, corriere mancante
Su 10, ma anche 11, sul partner e sull'ordine di vendita è possibile specificare i dati di spedizione che verranno poi riportati sul DDT.

Questi vengono riportati correttamente se si usa il flag "crea automaticamente il ddt" sull'ordine, ma se si passa dal wizard "DDT da Picking", il campo "corriere" ad esempio, non viene riportato.

# Fixes

 - [ ] v8:
 - [x] v10: #1044
 - [x] v11: #1103 
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1111

### PR DESCRIPTION
**Pull request by GSLabIt**
Add the carrier_id in ddt_from_picking, see https://github.com/OCA/l10n-italy/issues/1043

### CODE REVIEW

**Comment by GSLabIt** [comment]
@tafaRU ho preso la f0258a151179503e70258d5c779917f8ee12df69

**Comment by tafaRU** [comment]
@GSLabIt https://github.com/OCA/l10n-italy/commit/f0258a151179503e70258d5c779917f8ee12df69 fa riferimento ad un'altra PR :confused:

**Comment by GSLabIt** [comment]
Si scusa, intendevo dalla v 12.0

**Comment by GSLabIt** [comment]
Chiudo e riapro anche questa ..

**Pull request closed without merging**
