### PR TITLE
[l10n_it_ricevute_bancarie_report] aggiunto report sintetico totali scad...

### PR DESCRIPTION
**Pull request by scigghia**
...enze

### CODE REVIEW

**Comment by max3903** [comment]
@scigghia Can you fix PEP8 errors ?

**Comment by scigghia** [comment]
Sure! 
Asap

**Comment by dcorio** [comment]
@max3903 @eLBati i don't know the english translation of "ricevuta bancaria" (literally "bank receipt", that i wouldn't use) but in France there's a very similar procedure which is the lettre de change relevé.

**Comment by scigghia** [comment]
@eLBati @dcorio what is missing here?

**Comment by eLBati** [comment]
@scigghia it seems this https://github.com/OCA/l10n-italy/pull/28#issuecomment-73296857

**Comment by eLBati** [comment]
But, as 6.1 is full of PEP8 errors and the lines of code modified by this PR do not introduce new errors, I think it can be merged as is
@max3903 what do you think?

**Comment by tafaRU** [comment]
> I think it can be merged as is

I'm in favour too :+1:

**Comment by paolovalier** [comment]
:+1:

**Pull request merged**
