### PR TITLE
[12.0] l10n_it_bill_of_entry bolle doganali

### PR DESCRIPTION
**Pull request by eLBati**
From https://github.com/OCA/l10n-italy/pull/381

This module enables to manage extraUE import purchases, generating a bill of entry
according to the supplier invoice.

It involves three documents:

* Supplier Invoice
* Forwarder Invoice
* Bill of Entry

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

### CODE REVIEW

**Comment by TheMule71** [comment]
Ciao, ha senso aggiungerlo alla task list nella issue di migrazione alla 14?

**Review by andreampiovesana — APPROVED** [review]
go

**Review by mrcast — APPROVED** [review]
Functional test ok

**Pull request merged**
