### PR TITLE
[12.0][FIX] l10n_it_fatturapa_out: Fix error tests to copy files

### PR DESCRIPTION
**Pull request by victoralmau**
Fix error tests to copy files

Please @pedrobaeza review it

@Tecnativa TT26985

### CODE REVIEW

**Comment by eLBati** [comment]
When does the error happen?

**Comment by pedrobaeza** [comment]
And why a copy of the file is needed?

**Comment by victoralmau** [comment]
Errors happen to run tests.
I don't understand code (reason to copy file and why only error happen only in some case) but it's my fast fix it.

**Comment by pedrobaeza** [comment]
@eLBati can you clarify what is the goal of such copy to see if this can be improved in any way?

**Comment by eLBati** [comment]
:thinking: I found the commit which introduced it ec69c24a0054b9a1047ed58aae04dbbf34f8e5fe but I don't remember the reason.
Maybe @archetipo ?

Anyway, if tests run correctly without the copy, I guess we can directly remove it

**Review by eLBati — APPROVED** [review]
Thanks

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
