### PR TITLE
[FW][16.0]l10n_it_delivery_note_batch: forward-port of https://github.com/OCA/l10n-italy/pull/3821

### PR DESCRIPTION
**Pull request by PicchiSeba**
Forward-port di https://github.com/OCA/l10n-italy/pull/3821

Adattata alla versione 16.0

Fa riferimento a https://github.com/OCA/l10n-italy/issues/3639

### CODE REVIEW

**Review by Borruso — APPROVED** [review]
LGTM

**Review by aleuffre — APPROVED** [review]
Code review, LGTM

**Comment by aleuffre** [comment]
Fatto rebase per risolvere i conflitti

**Comment by francesco-ooops** [comment]
@Borruso puoi lanciare il merge?

**Pull request merged**
