### PR TITLE
[16.0] [ADD] l10n_it_vat_registries_rc: Integrazione l10n_it_vat_registries e l10n_it_reverse_charge

### PR DESCRIPTION
**Pull request by eLBati**
Dipende da https://github.com/OCA/l10n-italy/pull/3972

### CODE REVIEW

**Comment by mrcast** [comment]
@eLBati andando su runboat i moduli non sono installati e installando l10n_it_vat_registries_rc ottengo

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1633, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1660, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1864, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-77>", line 2, in button_immediate_install
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(self.env.registry[self._name].button_install)
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 599, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/opt/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/opt/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 488, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/odoo/modules/loading.py", line 231, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/opt/odoo/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/opt/odoo/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/opt/odoo/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/opt/odoo/odoo/tools/convert.py", line 709, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing None:6
Error while validating view:

Element '<xpath expr="//t[@t-set=&#39;partner&#39;]">' cannot be located in parent view

View error context:
{'file': '/mnt/data/odoo-addons-dir/l10n_it_vat_registries_rc/report/report_registro_iva.xml',
 'line': 2,
 'name': 'report_registro_iva_rc',
 'view': ir.ui.view(792,),
 'view.model': False,
 'view.parent': ir.ui.view(783,),
 'xmlid': 'report_registro_iva_rc'}


The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://oca-l10n-italy-16-0-pr4023-40415718c1cf.runboat.odoo-community.org/web/assets/416-f7a9e0e/web.assets_backend.min.js:993:163)
    at XMLHttpRequest.<anonymous> (http://oca-l10n-italy-16-0-pr4023-40415718c1cf.runboat.odoo-community.org/web/assets/416-f7a9e0e/web.assets_backend.min.js:1001:13)

**Comment by eLBati** [comment]
Direi perchè https://github.com/OCA/l10n-italy/pull/4023#issue-2173694968

**Comment by SirAionTech** [comment]
> Direi perchè [#4023 (comment)](https://github.com/OCA/l10n-italy/pull/4023#issue-2173694968)

Forse https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference(s)-to-another-pull-request(s) risolverebbe?

**Review by Esa199 — APPROVED** [review]
Test case it's ok

**Review by MaurizioPellegrinet — APPROVED** [review]
LGTM

**Pull request merged**
