### PR TITLE
[10.0] FIX l10n_it_account_stamp: recompute taxes when adding stamp to lines

### PR DESCRIPTION
**Pull request by eLBati**
This is needed as stamp line should be under VAT exemption

v12: https://github.com/OCA/l10n-italy/pull/818

### CODE REVIEW

**Comment by eLBati** [comment]
> Could you please add a test?

@SimoRubi The module does not have tests at all and at the moment I don't have time to add them.

> why not take advantage of https://github.com/odoo/odoo/blob/10.0/addons/account/models/account_invoice.py#L457-L463 (that is what happens when you manually add an invoice line)?

Because `compute_taxes` has been created for this scope and calling an `onchange` method would not write to DB.

**Comment by SimoRubi** [comment]
A little more research makes me realize that you are right and `compute_taxes` is generally used when adding a new invoice line.
My concern was that in the method it is specified that it is to be used on a **fresh** (just created) invoice. Too bad it is not done automatically by Odoo core (at least [they know that too](https://github.com/odoo/odoo/blob/10.0/addons/sale/models/sale.py#L386-L387)).

Too bad for automated tests too, ok then.

**Comment by tafaRU** [comment]
@SimoRubi please also review https://github.com/OCA/l10n-italy/pull/818

**Comment by SimoRubi** [comment]
Does this need to be backported to v8 too?

**Pull request merged**
