### PR TITLE
FIX  l10n_it_ricevute_bancarie group invoices

### PR DESCRIPTION
**Pull request by eLBati**
https://github.com/OCA/l10n-italy/issues/170

-> Install the module l10n_it_ricevute_bancarie
-> On tab Accounting of parter activate "Group Ri.Ba." and set payment as "RiBA 30 Days End of Month"
-> Create new customer invoice, insert a line and validate
-> From Ri.Ba -> Issue RiBa -> Select the line of relative invoice -> Wizard "Salvo buon fine" -> Error

### CODE REVIEW

**Comment by tafaRU** [comment]
Tested on runbot :+1:

**Comment by zeroincombenze** [comment]
Ma è stata risolta?

**Comment by zeroincombenze** [comment]
:+1: 
Testata in ambiente locale

**Comment by scigghia** [comment]
:+1:

**Comment by OpenCode** [comment]
:+1:

**Pull request merged**
