### PR TITLE
[14.0][FIX] l10n_it_fatturapa_in: fix invalid URIs

### PR DESCRIPTION
**Pull request by TheMule71**
Adattamento di #2940 per la 14.0

Co-authored-by: Borruso <gborruso@dinamicheaziendali.it>

### CODE REVIEW

**Review by Borruso — APPROVED** [review]
LGTM

**Review by tafaRU — APPROVED** [review]

**Comment by tafaRU** [comment]
> your merge command was aborted due to failed check(s),

Correzione: https://github.com/OCA/l10n-italy/pull/2976

**Pull request merged**
