### PR TITLE
[FIX] not existing css was used

### PR DESCRIPTION
**Pull request by dcorio**
the report template was using a wrong and not existing css file

### CODE REVIEW

**Comment by eLBati** [comment]
Are the changes to js related to the wrong css file?

**Comment by dcorio** [comment]
@eLBati i didn't touch the js code. just indented the <template> block

**Comment by eLBati** [comment]
thanks :+1:

**Comment by eLBati** [comment]
Oops, just tried to print VAT registers and got
[l10n_it_vat_registries.report_registro_iva.pdf](https://github.com/OCA/l10n-italy/files/45135/l10n_it_vat_registries.report_registro_iva.pdf)
So, that CSS should be anyway included by ```l10n_it_vat_registries``` or by ```l10n_it_account``` with another name
:-1: for now

**Comment by dcorio** [comment]
@eLBati thanks for the test. this is clearly a bug of the l10n_it_vat_registries modules. we should add that CSS in l10n_it_vat_registries since those classes aren't shared among the reports but vat registries specific. We then first fix l10n_it_vat_registries. cc: @DAMilani

**Comment by eLBati** [comment]
No activity for more than 6 months, closing. Feel free to reopen

**Pull request closed without merging**
