### PR TITLE
[14.0][FIX] l10n_it_vat_payability: replace script migration by pre_init_hook

### PR DESCRIPTION
**Pull request by tafaRU**
See commit message for further info.

### CODE REVIEW

**Comment by tafaRU** [comment]
Tested as follows:

```
git checkout d1437a38c56646410beed428ec5f854a47ae145f
Nota: eseguo il checkout di 'd1437a38c56646410beed428ec5f854a47ae145f'.

Sei nello stato 'HEAD scollegato'. Puoi dare un'occhiata, apportare modifiche
sperimentali ed eseguirne il commit, e puoi scartare qualunque commit eseguito
in questo stato senza che ciò abbia alcuna influenza sugli altri branch tornando
su un branch.

Se vuoi creare un nuovo branch per mantenere i commit creati, puoi farlo
(ora o in seguito) usando l'opzione -c con il comando switch. Ad esempio:

  git switch -c <nome nuovo branch>

Oppure puoi annullare quest'operazione con:

  git switch -

Disattiva questo consiglio impostando la variabile di configurazione
advice.detachedHead a false

HEAD si trova ora a d1437a38c [MIG] l10n_it_esigibilita_iva: Migration to 14.0
```

install `l10n_it_esigibilita_iva`

```
git checkout 14.0-fix-l10n_it_vat_payability
```

install `l10n_it_vat_payability`:

```
2021-04-28 12:00:35,915 116446 INFO ? odoo: Odoo version 14.0 
2021-04-28 12:00:35,915 116446 INFO ? odoo: Using configuration file at /home/tafaru/dev/envs/odoo14/etc/odoo14.cfg 
2021-04-28 12:00:35,915 116446 INFO ? odoo: addons paths: ['/home/tafaru/dev/envs/odoo14/odoo/odoo/addons', '/home/tafaru/.local/share/Odoo/addons/14.0', '/home/tafaru/dev/envs/odoo14/odoo/addons', '/home/tafaru/dev/envs/odoo14/l10n-italy', '/home/tafaru/dev/envs/odoo14/product-attribute', '/home/tafaru/dev/envs/odoo14/account-financial-tools', '/home/tafaru/dev/envs/odoo14/account-financial-reporting', '/home/tafaru/dev/envs/odoo14/server-ux', '/home/tafaru/dev/envs/odoo14/server-tools', '/home/tafaru/dev/envs/odoo14/partner-contact', '/home/tafaru/dev/envs/odoo14/account-invoicing'] 
2021-04-28 12:00:35,915 116446 INFO ? odoo: database: default@default:default 
2021-04-28 12:00:36,047 116446 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2021-04-28 12:00:36,123 116446 INFO test-l10n_it_esigibilita_iva odoo.modules.loading: loading 1 modules... 
2021-04-28 12:00:36,135 116446 INFO test-l10n_it_esigibilita_iva odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2021-04-28 12:00:36,211 116446 INFO test-l10n_it_esigibilita_iva odoo.modules.loading: updating modules list 
2021-04-28 12:00:36,213 116446 INFO test-l10n_it_esigibilita_iva odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via n/a 
2021-04-28 12:00:36,614 116446 INFO test-l10n_it_esigibilita_iva odoo.addons.base.models.ir_module: ALLOW access to module.button_install on ['l10n_it_vat_payability'] to user __system__ #1 via n/a 
2021-04-28 12:00:36,658 116446 WARNING test-l10n_it_esigibilita_iva odoo.modules.graph: module l10n_it_esigibilita_iva: not installable, skipped 
2021-04-28 12:00:36,662 116446 INFO test-l10n_it_esigibilita_iva odoo.modules.loading: loading 39 modules... 
2021-04-28 12:00:36,830 116446 INFO test-l10n_it_esigibilita_iva odoo.modules.loading: 39 modules loaded in 0.17s, 0 queries (+0 extra) 
2021-04-28 12:00:36,832 116446 INFO test-l10n_it_esigibilita_iva odoo.modules.loading: loading 40 modules... 
2021-04-28 12:00:36,832 116446 INFO test-l10n_it_esigibilita_iva odoo.modules.loading: Loading module l10n_it_vat_payability (33/40) 
2021-04-28 12:00:37,057 116446 DEBUG test-l10n_it_esigibilita_iva OpenUpgrade: 1 rows affected after 0:00:00.000246 running UPDATE ir_model_data SET module = 'l10n_it_vat_payability', name = 'view_tax_code_payability_form' WHERE module = 'l10n_it_esigibilita_iva' and name = 'view_tax_code_esigibilita_form' 
2021-04-28 12:00:37,058 116446 DEBUG test-l10n_it_esigibilita_iva OpenUpgrade: 0 rows affected after 0:00:00.000245 running DELETE FROM ir_model_constraint WHERE module = 127 
2021-04-28 12:00:37,058 116446 DEBUG test-l10n_it_esigibilita_iva OpenUpgrade: 0 rows affected after 0:00:00.000179 running DELETE FROM ir_model_relation WHERE module = 127 
2021-04-28 12:00:37,058 116446 DEBUG test-l10n_it_esigibilita_iva OpenUpgrade: 8 rows affected after 0:00:00.000239 running UPDATE ir_model_data SET module = 'l10n_it_vat_payability' WHERE module = 'l10n_it_esigibilita_iva' AND name NOT IN (SELECT name FROM ir_model_data WHERE module = 'l10n_it_vat_payability') 
2021-04-28 12:00:37,059 116446 DEBUG test-l10n_it_esigibilita_iva OpenUpgrade: 0 rows affected after 0:00:00.000220 running UPDATE ir_model_data SET name = name || '_openupgrade_' || id, module = 'l10n_it_vat_payability' WHERE module = 'l10n_it_esigibilita_iva' 
2021-04-28 12:00:37,059 116446 DEBUG test-l10n_it_esigibilita_iva OpenUpgrade: 0 rows affected after 0:00:00.000169 running UPDATE ir_module_module_dependency SET name = 'l10n_it_vat_payability' WHERE name = 'l10n_it_esigibilita_iva' 
2021-04-28 12:00:37,059 116446 DEBUG test-l10n_it_esigibilita_iva OpenUpgrade: 0 rows affected after 0:00:00.000184 running UPDATE ir_translation SET module = 'l10n_it_vat_payability' WHERE module = 'l10n_it_esigibilita_iva' 
2021-04-28 12:00:37,059 116446 DEBUG test-l10n_it_esigibilita_iva OpenUpgrade: 0 rows affected after 0:00:00.000197 running UPDATE ir_module_module m1 SET state=m2.state, latest_version=m2.latest_version FROM ir_module_module m2 WHERE m1.name='l10n_it_vat_payability' AND m2.name='l10n_it_esigibilita_iva' AND m1.state='uninstalled' 
2021-04-28 12:00:37,060 116446 DEBUG test-l10n_it_esigibilita_iva OpenUpgrade: 1 rows affected after 0:00:00.000908 running DELETE FROM ir_module_module WHERE name = 'l10n_it_esigibilita_iva' 
2021-04-28 12:00:37,061 116446 DEBUG test-l10n_it_esigibilita_iva OpenUpgrade: 1 rows affected after 0:00:00.000179 running DELETE FROM ir_model_data WHERE module = 'base' AND model='ir.module.module' AND name = 'module_l10n_it_esigibilita_iva' 
2021-04-28 12:00:37,107 116446 INFO test-l10n_it_esigibilita_iva odoo.modules.registry: module l10n_it_vat_payability: creating or updating database tables 
2021-04-28 12:00:37,132 116446 INFO test-l10n_it_esigibilita_iva odoo.modules.loading: loading l10n_it_vat_payability/views/account_view.xml 
2021-04-28 12:00:37,208 116446 INFO test-l10n_it_esigibilita_iva odoo.modules.loading: Module l10n_it_vat_payability: loading demo 
2021-04-28 12:00:37,218 116446 INFO test-l10n_it_esigibilita_iva odoo.modules.loading: Module l10n_it_vat_payability loaded in 0.39s, 83 queries 
2021-04-28 12:00:37,218 116446 INFO test-l10n_it_esigibilita_iva odoo.modules.loading: 40 modules loaded in 0.39s, 83 queries (+0 extra) 
2021-04-28 12:00:37,472 116446 INFO test-l10n_it_esigibilita_iva odoo.modules.loading: Modules loaded. 
```

**Review by primes2h — APPROVED** [review]
LGTM

Grazie!

**Comment by primes2h** [comment]
Provato e funziona a dovere.

**Pull request merged**
