### PR TITLE
11.0 mig l10n it ddt

### PR DESCRIPTION
**Pull request by SilvioGregorini**

### CODE REVIEW

**Comment by SimoRubi** [comment]
@SilvioGregorini check the bots

**Comment by SimoRubi** [comment]
@SilvioGregorini still working on this?

**Comment by SilvioGregorini** [comment]
@SimoRubi yes, I'm trying to clean the commit history, which I messed up although trying (and failing) to follow the steps reported here: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0
Problem is, I'm not an expert on git.
I was thinking, as a last resort, to cancel this PR and create a new one (with a better commit history), leaving the migrated and updated module as it is now.
What do you think?
Maybe @eLBati too can help us in this...

**Comment by SimoRubi** [comment]
Hi @SilvioGregorini, I started my PR (https://github.com/OCA/l10n-italy/pull/588) to migrate this module: luckily I haven't accomplished anything yet because I noticed that the module `stock_picking_package_preparation` is still in v10.
Then I started migrating that one first in https://github.com/OCA/stock-logistics-workflow/pull/448 (feel free to review that).

The commit history of the PR https://github.com/OCA/l10n-italy/pull/588 is clean, maybe it is easier for you to create a PR towards my repository https://github.com/SimoRubi/l10n-italy/tree/11.0-mig-l10n_it_ddt and migrate the module in there.

Otherwise you can try to fix this commit history or create a new PR.

**Comment by SilvioGregorini** [comment]
@SimoRubi alright then, it might be a good idea to reunite all the work within your repo and use the PR #588.
I'll create a PR to your repo later this evening, then this PR can be cancelled.

**Pull request closed without merging**
