### PR TITLE
[9.0][WIP] l10n_it_base_location_geonames_import on 9.0

### PR DESCRIPTION
**Pull request by simahawk**
Tested it on odoo 9.0 by using this PR https://github.com/OCA/partner-contact/pull/231.
It works... anything else to do here?

### CODE REVIEW

**Comment by eLBati** [comment]
@OCA/community-maintainers do you know why is travis green even with
```
ERROR openerp_test openerp.modules.graph: module l10n_it_base_location_geonames_import: Unmet dependencies: base_location_geonames_import
```
?

**Comment by simahawk** [comment]
@eLBati any update on this?

**Comment by pedrobaeza** [comment]
Please check this more complete migration of base_location_geonames_import: https://github.com/OCA/partner-contact/pull/253

**Comment by tafaRU** [comment]
:+1:

**Comment by eLBati** [comment]
Restarted travis build and :green_heart: 
:+1:

**Pull request merged**
