### PR TITLE
[16.0][MIG] l10n_it_bill_of_entry

### PR DESCRIPTION
**Pull request by SirAionTech**
Migrazione standard.

### CODE REVIEW

**Comment by SirAionTech** [comment]
Inclusa https://github.com/OCA/l10n-italy/pull/3630

**Review by OpenCode — APPROVED** [review]

**Comment by SirAionTech** [comment]
Fatto rebase e incluso https://github.com/OCA/l10n-italy/commit/459c7ad8cc4ed21f2b0f0312034cced77c8c4848

**Comment by Marianna-Marasco** [comment]
Test funzionali ok!

**Comment by francesco-ooops** [comment]
@Marianna-Marasco puoi approvare come da step in https://www.odoo-italia.org/documentazione/14.0/sviluppo/review.html#revisione-tecnica ? Grazie!

**Review by Marianna-Marasco — APPROVED** [review]

**Pull request merged**
