### PR TITLE
[16.0][MIG] l10n_it_declaration_of_intent

### PR DESCRIPTION
**Pull request by tafaRU**

### CODE REVIEW

**Comment by elvise** [comment]
@tafaRU puoi verificare il runboat ?

**Comment by francesco-ooops** [comment]
> @tafaRU puoi verificare il runboat ?

mi sembra un problema comune a molte PR, ho chiesto a sbidoul qui: https://discord.com/channels/737652535149592587/761225067798462465/1049309010148466749

**Comment by tafaRU** [comment]
> ho chiesto a sbidoul qui: https://discord.com/channels/737652535149592587/761225067798462465/1049309010148466749

Grazie, attendiamo pertanto una sua risposta prima di provare a scatenare una nuova build.

**Comment by francesco-ooops** [comment]
@tafaRU da [discord](https://discord.com/channels/737652535149592587/761225067798462465/1049365598171312188): There was a certificate issue that I worked around yesterday evening. Please push something to retry and tell me if that works.

**Comment by francesco-ooops** [comment]
@elvise si può comunque accedere ai runboat da https://runboat.odoo-community.org/webui/builds.html?repo=OCA/l10n-italy&target_branch=16.0 (se reggono)

**Comment by tafaRU** [comment]
@francesco-ooops 
> (se reggono)

direi di no, purtroppo il log https://runboat.odoo-community.org/api/v1/builds/bfedf2679-9faf-401b-8341-803ef57fb6db/init-log resituisce **Internal Server Error**.

**Comment by andreampiovesana** [comment]
File "/home/odoo-dev/odoo-dev16/PR/l10n_it_declaration_of_intent/models/sale.py", line 28, in onchange_partner_id
    res = super(SaleOrder, self).onchange_partner_id()
AttributeError: 'super' object has no attribute 'onchange_partner_id'

**Review by andreampiovesana — CHANGES_REQUESTED** [review]
File "/home/odoo-dev/odoo-dev16/PR/l10n_it_declaration_of_intent/models/sale.py", line 28, in onchange_partner_id
res = super(SaleOrder, self).onchange_partner_id()
AttributeError: 'super' object has no attribute 'onchange_partner_id'

**Comment by tafaRU** [comment]
@andreampiovesana puoi ritestare?

**Comment by andreampiovesana** [comment]
> @andreampiovesana puoi ritestare?

OK

**Review by andreampiovesana — APPROVED** [review]
LGTM
test funzionale ok

**Pull request merged**
