### PR TITLE
[FIX] l10n_it_account: fix error during vat statement calculation

### PR DESCRIPTION
**Pull request by tafaRU**
Sostituisce https://github.com/OCA/l10n-italy/pull/2799 e risolve https://github.com/OCA/l10n-italy/issues/2577.

### CODE REVIEW

**Review by stefano-ooops — APPROVED** [review]
testato su runboat calcolo imposte e liquidazione iva funziona correttamente

**Review by francesco-ooops — APPROVED** [review]
funzionale ok

**Review by TheMule71 — APPROVED** [review]
LGTM

**Pull request merged**
