### PR TITLE
[11.0] FIX l10n_it_fatturapa_in ZeroDivisionError: float division by zero

### PR DESCRIPTION
**Pull request by eLBati**
while importing lines with price 0 and discount 0
See test

### CODE REVIEW

**Comment by tafaRU** [comment]
@eLBati please resolve conflicts.

**Comment by eLBati** [comment]
@tafaRU done, thanks

**Comment by tafaRU** [comment]
@eLBati please also increment the module version.

**Comment by eLBati** [comment]
@tafaRU done

**Pull request merged**
