### PR TITLE
[FIX] l10n_it_withholding_tax: compare amount with float_compare

### PR DESCRIPTION
**Pull request by tafaRU**

### CODE REVIEW

**Review by fredzamoabg — APPROVED** [review]

**Review by TheMule71 — APPROVED** [review]
LGTM

**Comment by matteoopenf** [comment]
> @TheMule71 The merge process could not start, because of exception 403 Must have admin access to view repository collaborators..

anche io altrove ho un messaggio simile qualcuno avrà rotto github?

**Comment by TheMule71** [comment]
> > @TheMule71 The merge process could not start, because of exception 403 Must have admin access to view repository collaborators..
> 
> anche io altrove ho un messaggio simile qualcuno avrà rotto github?

Così pare...

**Comment by eLBati** [comment]
https://github.com/OCA/l10n-italy/pull/2418/files#r710099163 ?

**Comment by TheMule71** [comment]
> https://github.com/OCA/l10n-italy/pull/2418/files#r710099163 ?

Se non erro, è la stessa situazione:

https://github.com/OCA/l10n-italy/pull/2418/files#r710792568

**Comment by eLBati** [comment]
:+1:

**Pull request merged**
