### PR TITLE
[16.0] FIX l10n_it_fatturapa_out: Unexpected child with tag 'Nome'

### PR DESCRIPTION
**Pull request by eLBati**
https://github.com/OCA/l10n-italy/issues/3925

### CODE REVIEW

**Review by tafaRU — APPROVED** [review]

**Review by MaurizioPellegrinet — APPROVED** [review]
LGTM

**Comment by andreampiovesana** [comment]
merge?

**Comment by francesco-ooops** [comment]
@eLBati v14 anche?

**Comment by eLBati** [comment]
> @eLBati v14 anche?

Mi pare di sì

**Comment by francesco-ooops** [comment]
@eLBati vai con la issue allora :)

**Comment by eLBati** [comment]
tosto https://github.com/OCA/l10n-italy/issues/3925

**Review by TheMule71 — APPROVED** [review]
LGTM

**Pull request merged**
