### PR TITLE
11.0-fix number page in footer when print report with more page

### PR DESCRIPTION
**Pull request by jado95**
Before this PR, number page in footer is wrong - if there are 2 page: page 1 of 1; in second page: page 2 of 2
After this PR, Number page in footer is right

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

### CODE REVIEW

**Comment by jado95** [comment]
@eLBati Creato issue con riferimento a questa PR

**Comment by eLBati** [comment]
@jado95 in quali stampe si verifica?

**Comment by jado95** [comment]
@eLBati In tutte le stampe.. preventivi, ordini di vendita, picking, ecc

**Pull request closed without merging**
