### PR TITLE
Some terms translated to english for better consistency

### PR DESCRIPTION
**Pull request by paolovalier**
I'll update italian translation on transifex soon
this replace PR #212

### CODE REVIEW

**Comment by tafaRU** [comment]
:+1:

**Comment by eLBati** [comment]
:+1: thanks

**Comment by andrea4ever** [comment]
:+1

**Comment by sergiocorato** [comment]
This commit was not ported to 9.0, was it intentional? A migration from 8.0 will not have translated terms

**Comment by eLBati** [comment]
10.0 neither. I think it is to port

**Pull request merged**
