### PR TITLE
[16.0][MIG] l10n_it_sdi_channel

### PR DESCRIPTION
**Pull request by Borruso**
Migration l10n_it_sdi_channel from 14.0 to 16.0

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

### CODE REVIEW

**Review by TheMule71 — APPROVED** [review]
LGTM (review tecnica)

**Review by tafaRU — CHANGES_REQUESTED** [review]
Puoi schiacciare i commit amministrativi? (Rif. https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate)

**Review by tafaRU — APPROVED** [review]

**Pull request merged**
