### PR TITLE
[11.0][FIX] l10n_it_corrispettivi_sale: Create corrispettivo even if invoic…

### LINKED ISSUE #835: [11.0] l10n_it_corrispettivi, non funziona ricevuta di acconto
Dall'ordine di vendita con cliente "usa corrispettivo" 
crea fattura>acconto>% o valore fisso> crea fattura anziché corrispettivo 

# fixes

 - [ ] v8: not available
 - [ ] v10:
 - [ ] v11: https://github.com/OCA/l10n-italy/pull/976
 - [ ] v12:

### PR DESCRIPTION
**Pull request by monen17**
…e is created by advance payment.
Fixes #835

### CODE REVIEW

**Comment by GSLabIt** [comment]
@monen17 did u test creating and SO and setting `Usa corrispettivo` on partner? It seems that corrispettivo is not taken in account on wizard. Could u double check and confirm?

**Comment by monen17** [comment]
> @monen17 did u test creating and SO and setting `Usa corrispettivo` on partner? It seems that corrispettivo is not taken in account on wizard. Could u double check and confirm?

@GSLabIt do you mean https://github.com/OCA/l10n-italy/issues/994 ?

**Comment by GSLabIt** [comment]
I mean, this:

1. set use corrispettivo in partner
2. create a sale order for the partner
3. from sale order create a receipt with down payment. 
4. check journal on receipt (actually it create an invoice instead of recepit). 

to fix it, what i did is: 
```
    @api.onchange('partner_id')
    def onchange_partner_corrispettivi_sale(self):
        self.update({
            'corrispettivi': self.partner_id.use_corrispettivi
        })
```

instead of: 
```
    @api.onchange('partner_id')
    def onchange_partner_corrispettivi_sale(self):
        self.corrispettivi = self.partner_id.use_corrispettivi
```

on sale.py

**Comment by monen17** [comment]
Thanks @GSLabIt for the review!
If the issue you describe is present in 11.0 you can create your own PR to fix it and that would be the standard approach.

Otherwise if the issue you are describing is related to the changes that I did in this PR, you can PR my branch https://github.com/monen17/l10n-italy/tree/11.0-fix-issue835 so I can include your fix keeping you as legitimate author.

**Comment by monen17** [comment]
@elvise this should fix the issue https://github.com/OCA/l10n-italy/issues/835 that you created long ago, could you please check? Thanks

**Comment by elvise** [comment]
> @elvise this should fix the issue #835 that you created long ago, could you please check? Thanks

Sure, how can i test?

**Comment by monen17** [comment]
> > @elvise this should fix the issue #835 that you created long ago, could you please check? Thanks
> 
> Sure, how can i test?

Follow step 4 of https://odoo-community.org/page/review, runbot should be ready in a few minutes

**Comment by SimoRubi** [comment]
@elvise sei riuscito a provare se queste modifiche risolvono #835?

**Pull request closed without merging**
