### PR TITLE
[FIX] Redundant inherit in balance report

### PR DESCRIPTION
**Pull request by OpenCode**
Descrizione del problema o della funzionalità:

Travis genera un sacco di commit per i file .pot del modulo account_balance_report

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

### CODE REVIEW

**Comment by rousseldenis** [comment]
> Descrizione del problema o della funzionalità:
> 
> Travis genera un sacco di commit per i file .pot del modulo account_balance_report
> 
> --
> Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

Ok so try an ocabot merge command

**Review by rousseldenis — APPROVED** [review]

**Review by matteoopenf — APPROVED** [review]

**Review by warp10 — APPROVED** [review]

**Comment by rousseldenis** [comment]
@OpenCode @eLBati If this fixes the 11.0 branch, you need to rebase https://github.com/OCA/l10n-italy/pull/2160 in order to have a good merge flow.

**Comment by OpenCode** [comment]
> @OpenCode @eLBati If this fixes the 11.0 branch, you need to rebase #2160 in order to have a good merge flow.

Sure :)

**Comment by rousseldenis** [comment]
@OpenCode @eLBati This is an issue on the naming you did on the reports...

Odoo already has on account module that report and the same field names: 

https://github.com/odoo/odoo/blob/11.0/addons/account/wizard/account_report_trial_balance.py#L8

which inherit that one :

https://github.com/odoo/odoo/blob/11.0/addons/account/wizard/account_report_common.py#L10

For translations, Odoo transforms the model name account.balance.report and account_balance_report to field_account_balance_report_<field_name> : for both !

As the first one is already loaded from account module, it detects that the field reference already exists, so suffixes by the id. 
That's the problem you have. On travis side, as the field id in DB is different on each build, the field reference for pot changes also.

My question: Why not having an italian based name for your reports ? l10n.it.account.balance.report for instance.

That will solve:

- First the travis problem
- Secondly, and the most important, the issues you can have to effectively translate those problematic fields.

**Comment by OpenCode** [comment]
> @OpenCode @eLBati This is an issue on the naming you did on the reports...
> 
> Odoo already has on account module that report and the same field names:
> 
> https://github.com/odoo/odoo/blob/11.0/addons/account/wizard/account_report_trial_balance.py#L8
> 
> which inherit that one :
> 
> https://github.com/odoo/odoo/blob/11.0/addons/account/wizard/account_report_common.py#L10
> 
> For translations, Odoo transforms the model name account.balance.report and account_balance_report to field_account_balance_report_<field_name> : for both !
> 
> As the first one is already loaded from account module, it detects that the field reference already exists, so suffixes by the id.
> That's the problem you have. On travis side, as the field id in DB is different on each build, the field reference for pot changes also.
> 
> My question: Why not having an italian based name for your reports ? l10n.it.account.balance.report for instance.
> 
> That will solve:
> 
>     * First the travis problem
> 
>     * Secondly, and the most important, the issues you can have to effectively translate those problematic fields.

I can try to change report name

**Comment by rousseldenis** [comment]
> I can try to change report name

Ok, that's the best approach.

For travis build, I think this is because a test fails there https://travis-ci.com/github/OCA/l10n-italy/jobs/490679770#L2213

So, ocabot redo the build to try merging (and so the field reference is different next time - comparing each commit for pot on the merge branch).

**Comment by OpenCode** [comment]
> > I can try to change report name
> 
> Ok, that's the best approach.
> 
> For travis build, I think this is because a test fails there https://travis-ci.com/github/OCA/l10n-italy/jobs/490679770#L2213
> 
> So, ocabot redo the build to try merging (and so the field reference is different next time - comparing each commit for pot on the merge branch).

My last commit changes the report name with a l10nit_ prefix.

This PR was rebased, so Travis can run code on python 3.6.

The error you linked, is fixed (I hope) in another PR: https://github.com/OCA/l10n-italy/pull/2160

**Comment by OpenCode** [comment]
@rousseldenis PR https://github.com/OCA/l10n-italy/pull/2160 merged and rebased here. I think now we have a complete situation in this PR, too.

**Comment by rousseldenis** [comment]
Situation is stable now:

New export : 

image

Current pot builds : 

image

**Review by rousseldenis — APPROVED** [review]

**Comment by eLBati** [comment]
@OpenCode @rousseldenis thanks!

@OpenCode Should this also be done for v12?

**Comment by OpenCode** [comment]
> @OpenCode @rousseldenis thanks!
> 
> @OpenCode Should this also be done for v12?

If we merge this one, we will do this for 12, too.

**Comment by OpenCode** [comment]
@rousseldenis @eLBati I think we can close this PR. Actually, branch 11.0 is working again, so we are sure that this isn't the reason. Are you agree?

**Comment by eLBati** [comment]
OK

**Comment by sergiocorato** [comment]
> Are you agree

Closing as requested.

**Pull request closed without merging**
