### PR TITLE
[12.0] IMP l10n_it_fatturapa_in: alert user when WT data are incoherent

### PR DESCRIPTION
**Pull request by eLBati**
https://github.com/OCA/l10n-italy/issues/1755

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

### CODE REVIEW

**Comment by sergiocorato** [comment]
minor direi?

**Comment by eLBati** [comment]
:+1:

**Comment by pedrobaeza** [comment]
There has been a problem with merge bot, but it's fixed now, so you can relaunch.

**Pull request merged**
