### PR TITLE
[14.0][FIX] l10n_it_fatturapa_in: Fixed singleton error on field computation

### PR DESCRIPTION
**Pull request by cloudition**
Fixes: https://github.com/OCA/l10n-italy/issues/2349

Descrizione del problema o della funzionalità:

Comportamento attuale prima di questa PR:

Comportamento desiderato dopo questa PR:

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

### CODE REVIEW

**Comment by TheMule71** [comment]
Hi there!

Please run:
$ pre-commit run -a
review and add changed file(s)
$ git commit --amend
$ git push -f 
if you want to get rid of the pre-commit failed check.

If you're not familiar with the above procedure (which could be destructive if executed in the wrong repo/branch), please feel free to ask here.

**Comment by cloudition** [comment]
Hi,

I'm not an OCA member and I'm not familiar with your travis checks/deployment. I have fixed this issue locally for my customer and just wanted to report it here for you to know. The quick patch I just submited because I was asked to. I'm sorry but I have no more time to invest here... If you want you can reject/close the PR or take the code and submit it yourown :-)

**Comment by TheMule71** [comment]
> Hi,
> 
> I'm not an OCA member and I'm not familiar with your travis checks/deployment. I have fixed this issue locally for my customer and just wanted to report it here for you to know. The quick patch I just submited because I was asked to. I'm sorry but I have no more time to invest here... If you want you can reject/close the PR or take the code and submit it yourown :-)

No worries, thank you for your PR. Every contribution is more than welcome. :)

**Comment by TheMule71** [comment]
Closing, please refer to #2355

**Pull request closed without merging**
