### PR TITLE
[16.0] [FIX] l10n_it_declaration_of_intent: fix creditnote sign

### PR DESCRIPTION
**Pull request by Borruso**
Risolve: https://github.com/OCA/l10n-italy/issues/3055

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

### CODE REVIEW

**Review by tafaRU — APPROVED** [review]
Only technical review :+1: +1

**Review by marcelofrare — APPROVED** [review]
LGTM grazie!

**Review by primes2h — APPROVED** [review]
LGTM. Grazie!

**Pull request merged**
