### PR TITLE
[8.0][ADD] l18n_it_ipa

### PR DESCRIPTION
**Pull request by gigidn**
This module add the field ipa_code on res.partners. IPA-Code is a special code assigned to all public administration office and is a mandatory code for the electronic invoices for the italian PA.

### CODE REVIEW

**Comment by eLBati** [comment]
Any news on this?
@tafaRU do you want to upload the improvements you propose?
Otherwise we can merge I think

**Comment by gigidn** [comment]
Ops sorry, i forgot to post changes when merge ipa and other modules ... give me a few hours and i will post the update.

**Comment by tafaRU** [comment]
@gigidn about README.rst you can use https://github.com/OCA/maintainer-tools/tree/master/template/module

Thank you in advance.

**Comment by archetipo** [comment]
:+1:

**Comment by tafaRU** [comment]
I can propose my improvements later, in another PR, so :+1:
I proceed with the merge.

**Pull request merged**
