### PR TITLE
[FIX] fix issue#279

### PR DESCRIPTION
**Pull request by CiroBoxHub**

### CODE REVIEW

**Comment by OpenCode** [comment]
@eLBati **select** parameter in fields declaration generate the loop. if we delete **select** we solve the problem. The bug is in Odoo core.
https://github.com/OCA/OCB/blob/10.0/odoo/fields.py#L462

**Comment by eLBati** [comment]
I think ```select``` can be replaced by ```index```

**Comment by OpenCode** [comment]
@eLBati ok

**Comment by eLBati** [comment]
@CiroBoxHub prevedi di utilizzare ```index``` o preferisci lasciare la PR così com'è?

**Comment by CiroBoxHub** [comment]
@eLBati ho reinserito index per il field parent_id

**Comment by andrea4ever** [comment]
@eLBati mi sento tanto un'indovino in questo momento ;-)

**Comment by eLBati** [comment]
waiting for squash to merge

**Comment by eLBati** [comment]
squashed

**Pull request merged**
