### PR TITLE
[10.0][Fix] fiscalcode: Improve button feel to interface

### PR DESCRIPTION
**Pull request by drdran**
Hi, I have made a cosmetics improvement to the actual module, I have separated the button to calculate fiscalcode, to make it more readable

### CODE REVIEW

**Comment by eLBati** [comment]
@drdran please sign CLA

**Comment by drdran** [comment]
@eLBati CLA signed and approval reply received from OCA :)

**Comment by drdran** [comment]
@eLBati is possible that the OCABot don't refresh my subscritpion situation and not start to check the code?

**Comment by eLBati** [comment]
Maybe someone from @OCA/board knows?

**Comment by dreispt** [comment]
I confirm Franco Tampieri's ICLA.

**Comment by drdran** [comment]
@lasley 
Yes, I would like to try to retrigger the build

**Comment by drdran** [comment]
@lasley @eLBati 
I have no success to trigger update, so I think that I need to close this mp and open another, is right?

Regards

Franco

**Comment by lasley** [comment]
@drdran - I just triggered a rebuild on Travis and Runbot

**Comment by drdran** [comment]
Close PR and try again

**Comment by lasley** [comment]
@drdran - what was the problem here? Typically you want to stay in the same PR in order to not overly complicate things for reviewers. 

In this specific case, @eLBati has provided a review on code in this PR that is now in another. He'll now need to re-review the other PR - which is duplication of effort on his part.

This is a pretty tiny changeset, so it's not a big deal and you should just leave the other PR open. If there were a lot of changes though, an entire re-review can mean the difference of months for merge.

And most of all - welcome to the community + thank you for your contribution

**Comment by drdran** [comment]
@lasley Thank you for you feedback
I'm sorry but I did not want to create confusion, I did not understand why my MP was hanging and then just started Travis had given me errors that had not occurred before.

**Comment by dreispt** [comment]
Hi @drdran, please close the duplicate PR and continue with this one, since there is already review work done here.

**Comment by drdran** [comment]
Hi Travis told me that there is a Lint error, but don't report to me in which file is the lint error.

Can someone help me?

Regards

Franco

**Comment by lasley** [comment]
Click the fail and you get detailed output https://travis-ci.org/OCA/l10n-italy/jobs/310616047#L761

**Comment by drdran** [comment]
@lasley I see the output of travis, but indicate a generic linter error without detail :(

**Comment by dreispt** [comment]
@drdran Here are the lint errors: https://travis-ci.org/OCA/l10n-italy/jobs/310616047#L762-L764

**Comment by drdran** [comment]
Wow very strage, because the file l10n_it_ddt/models/stock_picking_package_preparation.py that raise the flake error:
l10n_it_ddt/models/stock_picking_package_preparation.py:193:17: E128 continuation line under-indented for visual indent

But that lines isn't in my patch. I have to fix it or I have to warn @elbati to check that problem?

Regards

Franco

**Comment by eLBati** [comment]
@drdran probably it was fixed meanwhile. You should try rebasing on top of OCA/10.0

**Comment by drdran** [comment]
Thats ok, after rebase with origin/10.0 branch now Travis tell me that all code test is ok.
@eLBati can u help me to make Coveralls run god? :)

Regards

Franco

**Comment by lasley** [comment]
I don't see any code here that should be affecting coverage, so that can be ignored IMO

**Comment by drdran** [comment]
@eLBati do u want that I rebase and squash the changeling of the MP ti approve it?

**Comment by eLBati** [comment]
Squashed and merged

**Pull request merged**
