### PR TITLE
[12.0] mig l10n_it_fatturapa_out

### PR DESCRIPTION
**Pull request by eLBati**
Depends on https://github.com/OCA/l10n-italy/pull/662

TODO
~~https://github.com/OCA/l10n-italy/pull/691~~
~~https://github.com/OCA/l10n-italy/pull/693~~
~~https://github.com/OCA/l10n-italy/pull/694~~
~~https://github.com/OCA/l10n-italy/pull/699~~
~~https://github.com/OCA/l10n-italy/pull/700~~
~~https://github.com/OCA/l10n-italy/pull/702~~

### CODE REVIEW

**Comment by primes2h** [comment]
Aperta la PR #674 da includere.

**Comment by eLBati** [comment]
@primes2h grazie, incluso https://github.com/OCA/l10n-italy/pull/663/commits/365ed89adec05a900dcdc2c4238302f53b38a5ea

**Comment by primes2h** [comment]
Da includere anche la #691.

**Comment by primes2h** [comment]
La #677 è merged, ci sarebbe da fare il cherry-pick di questo commit 926f1e6fd51f80cd1ca678a91af919dff6b92a5f

**Comment by primes2h** [comment]
Functional test:

- Create a new invoice
- Validate the invoice
- Click on "Export E-invoice"

You get the error
"Company does not have fiscal code or VAT number."
despite company VAT number has been set for the company.

**Comment by primes2h** [comment]
> @primes2h I can't reproduce the error.
> Consider that here 'company' is your company.

Ok, it's official. I need a break. :sweat:

**Comment by eLBati** [comment]
@primes2h :grin: do you think message should be improved with "your company"?

**Comment by primes2h** [comment]
> @primes2h  do you think message should be improved with "your company"?

In fact it's seems to be the Odoo standard, a lot of strings use that form. Make them uniform could be an improvement.

Nevertheless it was my fault, difference between company and partner is clear. :stuck_out_tongue:

**Pull request merged**
