### PR TITLE
[12.0] FIX l10n_it_fatturapa translations

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Comment by sbidoul** [comment]
@eLBati I just forced an update of the .po files from weblate.

I don't understand yet why it was not done automatically.

Sometimes it works, for example here:

image

**Comment by eLBati** [comment]
@sbidoul is https://translation.odoo-community.org/projects/l10n-italy-12-0/l10n-italy-12-0-l10n_it_fatturapa/it/ up to date? I still can't find some terms.
Example: `Organization Province` at https://github.com/OCA/l10n-italy/blob/12.0/l10n_it_fatturapa/models/account.py#L388
Thanks

**Comment by eLBati** [comment]
Here is the tried search:
https://translation.odoo-community.org/zen/l10n-italy-12-0/l10n-italy-12-0-l10n_it_fatturapa/it/?q=Organization+Province&search=ftx&source=1&target=1&type=all

**Comment by sbidoul** [comment]
It is in it.po. For sure text search indexes take time to refresh in weblate. Perhaps it needs some time to catch up with the update, as the update touched many .po files.

**Comment by eLBati** [comment]
I still can't find `Organization Province` at https://translation.odoo-community.org/projects/l10n-italy-12-0/l10n-italy-12-0-l10n_it_fatturapa/it/

**Comment by sbidoul** [comment]
`Organization Province` is in it.po, but weblate does not seem to pick it up. I don't know why...

**Comment by eLBati** [comment]
@sbidoul @primes2h meanwhile do you think we can merge this one https://github.com/OCA/l10n-italy/pull/710 ?

**Pull request closed without merging**
