### PR TITLE
[IMP]l10n_it_delivery_note: Add is_carrier on partner and domain

### PR DESCRIPTION
**Pull request by aleuffre**
https://github.com/OCA/l10n-italy/issues/3325 for 16.0

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

**Review by andreampiovesana — APPROVED** [review]
LGTM

**Review by marcelofrare — APPROVED** [review]
LGTM on runboat

**Comment by andreampiovesana** [comment]
@aleuffre puoi cambiare la label da draft a open, che poi facciamo il merge, grazie

**Review by OpenCode — APPROVED** [review]

**Pull request merged**
